from django.db import models

class Paths(models.Model):
    # "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TYPE_CHOICES = (
        ("FILE", "FILE"),
        ("DIRECTORY", "DIRECTORY"),
    )
    PathType = models.CharField(max_length=9,
                  choices=TYPE_CHOICES,
                  default="FILE")
    # PathType = models.TextChoices('DIRECTORY', 'FILE')
    # pathType = models.CharField(blank = False, choices = PathType.choices, max_length=10)
    name = models.CharField(max_length = 150)
    class Meta:
        db_table='Paths'

class Relations(models.Model):
    parent = models.ForeignKey(Paths,on_delete=models.CASCADE,related_name='parentInode')
    child = models.ForeignKey(Paths,on_delete=models.CASCADE, related_name='childInode')
    class Meta:
        db_table='Relations'

class Patitions(models.Model):
    # id is inode from Paths
    inode = models.ForeignKey(Paths, on_delete=models.CASCADE)
    location = models.CharField(max_length = 200)
    class Meta:
        db_table='Partitions'


