from django.db import models

class Paths(models.Model):
    # "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    PathType = models.TextChoices('DIRECTORY', 'FILE')
    #  store relative path name, could be duplicated
    name = models.CharField(max_length = 150)
    pathType = models.CharField(blank = False, choices = PathType.choices, max_length=10)
    class Meta:
        db_table='Paths'

class Relations(models.Model):
    parent = models.ForeignKey(Paths,on_delete=models.CASCADE,related_name='parentInode')
    child = models.ForeignKey(Paths,on_delete=models.CASCADE, related_name='childInode')
    class Meta:
        db_table='Relations'

class Patitions(models.Model):
    # id is inode from Paths
    inode = models.ForeignKey(Paths, on_delete=models.CASCADE)
    location = models.CharField(max_length = 200)
    class Meta:
        db_table='Partitions'


