# Generated by Django 4.1.3 on 2022-11-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
