# Generated by Django 3.2.16 on 2022-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City0',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=-1)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'City0',
            },
        ),
        migrations.CreateModel(
            name='City1',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=-1)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'City1',
            },
        ),
        migrations.CreateModel(
            name='City2',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=-1)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'City2',
            },
        ),
        migrations.CreateModel(
            name='Rate0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=256)),
                ('restId', models.CharField(max_length=256)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'Rate0',
            },
        ),
        migrations.CreateModel(
            name='Rate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=256)),
                ('restId', models.CharField(max_length=256)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'Rate1',
            },
        ),
        migrations.CreateModel(
            name='Rate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=256)),
                ('restId', models.CharField(max_length=256)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'Rate2',
            },
        ),
        migrations.CreateModel(
            name='Rest0',
            fields=[
                ('business_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('review_cnt', models.IntegerField()),
                ('city', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('categories', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Rest0',
            },
        ),
        migrations.CreateModel(
            name='Rest1',
            fields=[
                ('business_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('review_cnt', models.IntegerField()),
                ('city', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('categories', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Rest1',
            },
        ),
        migrations.CreateModel(
            name='Rest2',
            fields=[
                ('business_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('review_cnt', models.IntegerField()),
                ('city', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('categories', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Rest2',
            },
        ),
        migrations.CreateModel(
            name='User0',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'User0',
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'User1',
            },
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'User2',
            },
        ),
    ]
