# Generated by Django 3.2.16 on 2022-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city0',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city1',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city2',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rate0',
            name='restId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rate0',
            name='userId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rate1',
            name='restId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rate1',
            name='userId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rate2',
            name='restId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rate2',
            name='userId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rest0',
            name='business_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rest1',
            name='business_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rest2',
            name='business_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user0',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user2',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
