# Generated by Django 4.1.3 on 2022-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paths',
            name='pathType',
            field=models.CharField(blank=True, choices=[('FILE', 'File')], max_length=10),
        ),
    ]
