# Generated by Django 3.2.16 on 2022-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paths',
            name='inode',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
