# Generated by Django 4.1.3 on 2022-11-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paths_pathtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paths',
            name='pathType',
            field=models.CharField(choices=[('FILE', 'File')], max_length=10),
        ),
    ]
